spring:
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/simpme
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    open-in-view: false
    database: mysql
    show-sql: true

  liquibase:
    enabled: false
    change-log: db/changelog/changelog-master.xml
    default-schema: simpme

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true